### ISSUE TITLE
Gmic: add generic plugin?

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#128]
A generic Gmic plugin should be made, basic just like GmicExpr but using gmic commands.

I don't know if this should be made here or the work should be continued at https://github.com/MrKepzie/openfx-gmic (can't get it to build, don't know the status(untouched since 2014))

I got a simple POC plugin, it can read and manipulate the image, but returning the image does not work (not my best side, looping through pixels etc, just give me a "write" function ;) , maybe openfx-misc/Cimg has any pointers to that).

The plugin must of course be separated from the rest due to license (own bundle), and can't be distributed (?) with Natron.

Low priority.

**Comment by manuelsongokuh** [comment]
Hello, that is cool gmic..
but for me: better to close all that are open issues, close milestone one time, one time, step-step-step.
after will be add new ok?
need to manager time to close all isssue or all feature request old..except that all issues BUG, ok?
:-)

**Comment by olear** [comment]
Yupp, it's low pri. Just needed to add the issue so I don't forget.

**Comment by devernay** [comment]
Support for generic gmic commands would make things a lot more complicated (where do you read files from? where do you write images to?). GMIC commands are really meant to be used from the command-line.
A better idea IMHO would be to have a more constrained description, just like the gimp plugin or gmicol. This is what we started in openfx-gmic.
Just remember that, because of license issues, plugins that use gmic cannot (yet) be distributed with Natron.

**Comment by olear** [comment]
My plan was just a generic filter that takes gmic commands (-glow etc), reads the image, proc and deliver. The only thing I don't have working is the write part. As said (very) low priority (due to license and needs).
