### ISSUE TITLE
ReadSVG: DPI not changed during anim

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#143]
Changing the dpi param in an animation don't change the image size (well the canvas size is changed, but not the image content), remove anim and all is good.

**Comment by olear** [comment]
changedParam is not triggered (or anything) when an anim changes the param.

**Comment by olear** [comment]
happens in ReadOIIO also, host bug?

**Comment by olear** [comment]
@MrKepzie is this a generic reader problem? the param is changed, but changedparam is not triggered...

**Comment by devernay** [comment]
Your changedParam overloads the one in genericreader, so this can't be.
Animations don't trigger changedparam, that's all. You cannot rely on changedparam being called, you have to do the right thing in the render function.
The reason is: when you change the value of a keyframe, should we call changeparam for all affected times? And when we play a sequencw shoumd we call changedParam on every animated patam before calling rendre? Nobody does that. Just read thé value on pour rendre func.

Changedparam is for user feedback and gui stuff.

**Comment by olear** [comment]
Ok, seems I misunderstood changedparam, will adjust. Thanks for the information.

**Comment by devernay** [comment]
And sorry for the French spellchecking on my phone!

Le 29 août 2015 00:48:18 GMT+02:00, "Ole-André Rodlie" <notifications@github.com> a écrit :
>Ok, seems I misunderstood changedparam, will adjust. Thanks for the
>information.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/olear/openfx-arena/issues/143#issuecomment-135905390

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
