### ISSUE TITLE
Read*: dopesheet

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#145]
Unsure if this is a bug or not, but @blackearth2014 noted that ReadOIIO etc is added to the dopesheet on read, but ReadPSD/ReadSVG must be keyed to show up in the dopesheet.

Check if I'm missing something compared to the other readers.

**Comment by olear** [comment]
Can see anything in ReadOIIO vs. ReadPSD that affects this ...

**Comment by blackearth2014** [comment]
Here is an screen capture with both the ReadOIIO node vs ReadPSD node in the dopesheet panel. Only the ReadOIIO node is being displayed.  This is what I mean. If there is only one frame or just a still image, it won't show in the dopesheet. I don't have any PSD sequence images to see if it shows in the dope sheet panel to clarify otherwise, but I will continue beta testing it.

![readoiio vs readpsd - dopesheet](https://cloud.githubusercontent.com/assets/7956901/8890957/ec67a394-32e1-11e5-8b3e-80598361ee76.png)

**Comment by olear** [comment]
Currently not anything I can do in the plugin.
