### ISSUE TITLE
Plugin categories

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#149]
Got suggestion on mail regarding categories. The request was to move the plugins in filter (paintstuff) in 'FX'.

I don't care where stuff is, so use this issue to "agree" where stuff should be before 2.0.0 tag.

**Comment by blackearth2014** [comment]
I would to see your plugins in their category like ArenaOFX. Then in the category group you have subcategories for the various nodes. When you installed Genarts, they have their own category group.

**Comment by olear** [comment]
That works for third-party plugins, but when it's included in Natron it should adapt to the existing categories(?)

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by olear** [comment]
Current suggestions:

 * as-is
 * Move everything to Arena(OFX) category (and possible subcategories)
 * Move plugin Y to category X

**Comment by Ambassy** [comment]
These are plugins primarly designed for natron,so they must adapt the existing natron categories.

**Comment by manuelsongokuh** [comment]
Hello, for moment plug is ARENA will port in natron 2.0 stable, and you will begin to think will merge in natron 2.1 or 2.5 or 3.0 you are free of choose, for moment arena was fresh (more stable) but fresh word is for natron..
my case from your arena plug in my computer i did changed color of all icon (from white to green) because i can find as fast (color green icons), green for me : that is arena plug, if color white so i hard to my eyes to do to "search" or do to "read" , green for me as fast like detected plug of arena, i always changed from your snapshot arena: changed color green ok?

this is my case for me fast my jobs icon green for arena ok? you can start to think.. ok?

byebye

**Comment by olear** [comment]
I added some icons just to have something, they illustrate okish what they do ...

But Jean-Christophe Levet, the designer behind the other icons in Natron will "fix" my icons before release, so they will blend a bit more with the rest etc.

**Comment by olear** [comment]
Keep as-is, closed.
