### ISSUE TITLE
Circular Polarizing Filtering Effect: Request

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#168]
I know optically a Circular Polarizing Filter can only benefit in real situations. Is it possible to simulate it as a SMH coloring effect on over/under expose video footage or stills.

**Comment by manuelsongokuh** [comment]
do you have a demo or example to show here?

**Comment by blackearth2014** [comment]
No I don't. I am a videographer. I have filter's galore. My circular polarizer filter is 43mm for my SD camera that I can no longer capture with. I like the effect that it had when I would turn to get the right polarization.

**Comment by olear** [comment]
I don't know how to do this digitally, need some specs/info etc ...

**Comment by blackearth2014** [comment]
Then scratch it, because I have no clue about how to get the specs on that.

**Comment by manuelsongokuh** [comment]
Circular Polarizing mean: Polarizing_filter_(photography)?
if you dais Polarizing_filter_(photography): i respont
IMPOSSIBLE! because that is used lens special and shot in matrix sensor like as REAL RAW, when turn rotation of lens filter it' chenged this mean changed information of RAW sensor..
for computer digital it's impossible... i mean: computer digital see in future or computer like as God?
it's impossible.

because example:
![link-image](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/CarWindowPolarization.jpg/500px-CarWindowPolarization.jpg)
so i ask you: how computer digital knows all information raw..? like as ray-x ? impossible computer digital will know all the future...
i'm right or wrong?
thank you

**Comment by blackearth2014** [comment]
Like I said in my first post. I know it only benefits real world filming optically. It wouldn't make much sense once I'd thought about it because most likely circular polarizers would have already been applied during filming.
