### ISSUE TITLE
Polaroid Node: Enhancement

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#176]
Could the Polaroid Node get a Left, Center and Right alignment feature operator?

**Comment by olear** [comment]
Shouldn't be a problem, on text or the complete image?

**Comment by blackearth2014** [comment]
Both if possible, but the text is more important to me.

Thanks

**Comment by olear** [comment]
Ok, will add more text features.

**Comment by blackearth2014** [comment]
If you can add some of the features from your TextOFX into the Polaroid Node, that could be helpful.

**Comment by olear** [comment]
No problem :)

**Comment by blackearth2014** [comment]
Thanks

**Comment by olear** [comment]
text align is not supported in the function in ImageMagick, but I have a workaround, requires a patch to ImageMagick...

**Comment by olear** [comment]
Hit a minor issue, and I need to modify IM more than I though, currently put on hold until I find a better solution.

**Comment by blackearth2014** [comment]
Cool Breeze. Since the TextOFX has a positioning transform overlay, can you just activate a transform overlay. This way we can align what we want without a prefixed alignment code?

**Comment by olear** [comment]
The problem is that I use an existing function in ImageMagick, any new features (beyond what's available) must be added in ImageMagick. Align is no problem if I hardcode it in ImageMagick, but getting the plugin to "communicate" with the polaroid function (beyond what's available) in ImageMagick is a bit tricky, will look into this a bit later today. 

I also don't want to modify too much in ImageMagick, I want to stay as close to upstream as possible.

**Comment by blackearth2014** [comment]
Cool Breeze.

**Comment by olear** [comment]
Future development using ImageMagick has stopped, so this node is EOL (no more features will be added, still supported).

I may rewrite this node at a later date, but it's low on my TODO list.

**Comment by blackearth2014** [comment]
Cool Breeze
