### ISSUE TITLE
why natron split out arena-fx in menu effect?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#181]
today snapshot, arena fx is out of filter list effect..?

**Comment by olear** [comment]
This was done by request.

**Comment by manuelsongokuh** [comment]
where is commits from natron?

**Comment by manuelsongokuh** [comment]
because i'm confused, because before i use filter and transform instead all in one group named arene..then for future Arena ever or again to change?

**Comment by olear** [comment]
I don't care where they are, as long as they are available :) But ... I got a request to move the plugins out of Filters, and I did. I also moved plugins out of Transform (since I guess I will probably get a request regarding that as well).

Text/TextPango are still in 'Draw' and ReadSVG/ReadPSD are still in 'Image/Readers', the rest are now in 'Arena'.

**Comment by olear** [comment]
Closed, see #149

**Comment by manuelsongokuh** [comment]
ok, it's possible go to better:
arena>transform>arc
arena>transform>polar
arena>filter>...
arena>texture>....
?

**Comment by olear** [comment]
possible, but I don't think we have enough plugins to warrant subcategories?

**Comment by manuelsongokuh** [comment]
ok, that is idea propostal ok? thank you
