### ISSUE TITLE
TextPango & TextOFX Feature request

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#187]
Is it possible to implement a feature that was in the TextOIIO node were as you can connect a Read node to it and the text overlaid onto it. You didn't have to use a merge node like you have to do with the TextPango and TextOFX.

**Comment by olear** [comment]
I had that function in a early version, but was removed since it introduced some issues in ImageMagick.

TextOFX+Pango is strictly generators.

Note that I have started a complete rewrite (TextFX in openfx-extra), will probably be available in v2.1 (I hope, if not then in v3).

**Comment by MrKepzie** [comment]
We should I think write a complete Text plug-in based only on Freetype and ditch most of IM if possible

**Comment by blackearth2014** [comment]
Okay. Its not a show stopper.

**Comment by olear** [comment]
@MrKepzie : I'm doing a rewrite using pangocairo.

**Comment by olear** [comment]
As a extra note. TextOFX is feature complete, I can't add more features with current backend. I can still change stuff, but I have come to a dead-end regarding new text/font features. The move to pango+cairo gives me (in theory) unlimited options regarding text/font stuff, so most demand can be added (in time, I got to start from scratch (using a new backend)). TextPango will be also written from scratch or merged into TextFX (most likely).

**Comment by blackearth2014** [comment]
TextPango should be merged with TextOFX as an additional animatable feature.

**Comment by olear** [comment]
Btw, got input working in TextPango, will test some more.

Currently TextOFX and TextPango has been separated since TextPango don't support renderscale (I had problems switching renderscale in TextOFX with TextPango merged, but that was some months ago, and maybe it now works in Natron). If that works there are no problems merging the two.

**Comment by blackearth2014** [comment]
Cool Breeze. By the way, will your new text nodes have premultiplication implemented for anti-aliasing on the edges. I have to use the premult node to get that smooth look.

**Comment by olear** [comment]
TextOFX/TextPango has anti-aliasing.
![snapshot16](https://cloud.githubusercontent.com/assets/7461595/10371290/ec5c78d4-6de2-11e5-94e8-2f006e7f042f.png)

**Comment by blackearth2014** [comment]
This is what it looks like on the Mac w/o Premult.

![brick masnsions](https://cloud.githubusercontent.com/assets/7956901/10371682/7d79e9d6-6db2-11e5-833c-5a84b5cd2474.png)

**Comment by olear** [comment]
On Win7 I get this:
![textwin](https://cloud.githubusercontent.com/assets/7461595/10372465/28d87966-6de8-11e5-892d-5ac10c64dcfb.png)

TextPango still has issues, but not TextOFX.

This is a deployment/build issue.

**Comment by olear** [comment]
@blackearth2014 The Arena.ofx plugins are built against a wrong ImageMagick version, that's why you have issues.
![snow leopard](https://cloud.githubusercontent.com/assets/7461595/10413534/18dcc104-6fad-11e5-8b07-93951a0ff5c2.png)

**Comment by blackearth2014** [comment]
Okay! Did you inform Alex and Fred about your nodes being build against the wrong imagemagick libraries?

**Comment by olear** [comment]
Will notify. For reference, version 6.8.10-1 is the version you want in the about window.

**Comment by devernay** [comment]
Hey I'm reading this too !

I didn't know there was an upgrade to that patched IM version. I will integrate these next week (may take time, I have a very busy week).

I'm using a more recent imagemagick here anyway (6.9.something), so I don't get the patches that Ole made to the IM sources, and can't use/test these nodes on my development machine.

fred

**Comment by devernay** [comment]
version 6.8.9-10 + the patches 
- https://github.com/MrKepzie/Natron/blob/workshop/tools/MacOSX/ports/graphics/ImageMagick/files/magick-seed.diff
- https://github.com/MrKepzie/Natron/blob/workshop/tools/MacOSX/ports/graphics/ImageMagick/files/magick-svg.diff

seems to be exactly what you call 6.8.10-1 (which was never released). I diffed the sources myself.

So *no*, Natron on OSX is not build against the wrong imagemagick version.

The issue, as @blackearth2014 mentionned, is really premult.

First of all, the output of TextOFX is marked as "Opaque", which is obviously wrong. This can easily be fixed in getClipPreferences, but this may also be a bug in Natron, @MrKepzie (the "Ramp" plugin also claims its output is Opaque, whereas it should be UnPremultiplied when alpha is checked from RampPlugin::getClipPreferences.)

Second, the output of TextOFX is really UnPremultiplied, not Premultiplied, so that the "matte" Merge operator has to be used instead of Merge. Even in your screenshots @olear the merge seems to be wrong. Can you please check that? AFAIK ImageMagick never used premultiplied images, so premultiplication probably has to be done in your plugin code.

You should probably add a "premult" checkbox in your plugin codes to handle output premultiplication, i.e is a ClipPreferencesSlaveParam and is handled in getClipPreferences and render.

**Comment by olear** [comment]
I'm testing latest IM with premult. Will probably have something working soon.

**Comment by olear** [comment]
So I think I got this working, using vanilla ImageMagick 6.9.2-4 (latest stable):
![snapshot1](https://cloud.githubusercontent.com/assets/7461595/10419850/699e907c-7084-11e5-81f1-b1dd53ab2d0c.png)

**Comment by blackearth2014** [comment]
Looking good.

**Comment by olear** [comment]
I also added support for source clip.

**Comment by blackearth2014** [comment]
Thanks Olear

**Comment by devernay** [comment]
Hurray!
