### ISSUE TITLE
Olear's Nodes: Doesn't load

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#197]
Olear,

This latest Mac snapshot Natron-201510221904-215992d057d9c2fe2cc5976e0f7072cbf6cbbe29.dmg does't load your plugins. See the attached image for the pop up error screen. This is happening for all of your nodes in this release.

![waves node](https://cloud.githubusercontent.com/assets/7956901/10682467/0d48fe7e-7904-11e5-9ef8-dd244822ee4b.png)

**Comment by olear** [comment]
Natron-201510221904-215992d057d9c2fe2cc5976e0f7072cbf6cbbe29.dmg :
![snow leopard](https://cloud.githubusercontent.com/assets/7461595/10682614/f474fcde-7937-11e5-9a9a-537d1ed5c582.png)

I didn't change anything, so probably a build issue((?) a bit strange since it works here). Try removing the cache xml.

**Comment by blackearth2014** [comment]
I keep forgetting about the Clear plugin cache feature.  I wish there was a way to have that done automatically on every launch of the app.
