### ISSUE TITLE
Heads-up: plugin id changes(?)

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#202]
Since ArenaOFX started the plugins has been identified with net.fxarena.openfx.ID, but since my involvement in FxArena has changed, I will transfer the copyright to myself. Due to that using the fxarena.net domain seems a bit odd, I will start using the openvfx.org domain (org.openvfx.plugins.ID) if nobody has any objections.

This will break existing projects, but should be easy to fix, a 'sed' replace on the NTP should be enough.

```
sed "s/net.fxarena.openfx/org.openvfx.plugins/g" myproject.ntp
```

If there are any/many objections I will consider keeping the old ID on existing plugins until Natron v3 (but new plugins will get new ID).

**Comment by devernay** [comment]
plugin ids should *never* change... does the fact that there is fxarena somewhere in a string bother you?
one solution would be:
- declare them with the  net.fxarena.openfx ID, and mark these as kNatronOFXImageEffectPropDeprecated, so they can still be instanciated but do not apprear in the Natron GUI
- also declare them with the new ID, so that whenever they are instanciated they appear with the new ID.

**Comment by olear** [comment]
Ok, will keep as-is.
