### ISSUE TITLE
ReadKrita: Layers and Animation (keyframes) support

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#215]
See https://github.com/MrKepzie/Natron/issues/1109

Currently the plugin only supports the merged image from Krita, the following features are wanted/needed:

- Multi-plane support
- Animation/Keyframe support

Challenges:

- The layers in Krita are binary blobs, need to find out how to read/convert them to something usable
- Keyframes are "sub" layers for each layer (layername.fX, where X is the keyframe), making a composite of all the layers for each frame can be a bit problematic
- The Animation part is not complete in Krita

**Comment by boudewijnrempt** [comment]
It's going to be _really_ tough to take the individual layers and compose them in exactly the same way Krita does, not only because we kinda forgot to keep the documentation properly updated, but also because with file layers, clone layers, filter layers and masks and so on, recalculating the merged image from scratch is going to be as hard or harder as the same task for psd files.

**Comment by olear** [comment]
Yeah, found out last week when testing, will not give up, but this is a "sometime in the future" TODO.

Thanks for your input :+1:

**Comment by mamarilmanson** [comment]
"The future of Animation in Linux..."

XD

**Comment by olear** [comment]
After some serious testing I don't think this is reasonable, I will never get the merges right, and the plugin will be slow. 

A better solution would be if Krita could export animation as image sequence (EXR/ORA) with layers.
