### ISSUE TITLE
Split Distort into individual plugins?

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#59]
Distort includes Polar, Arc, Swirl, Implode, Wave  etc. Should the effects be separated into individual plugins?

Pros: Better overview for the user. Swirl swirls, wave waves etc
Cons: Code bloat

**Comment by rcspam** [comment]
For me keep in a brundle is more teaching and learning.
Regards

**Comment by manuelsongokuh** [comment]
not separated, can care space of UI i did send you days ago..see this issues:
![natron-distort](https://cloud.githubusercontent.com/assets/12126929/7779938/87b93884-00d9-11e5-8a32-39ed2ee0bffb.jpg)

this is best for UI and fast during working composite..

**Comment by manuelsongokuh** [comment]
this is problem for "Code bloat"?

**Comment by olear** [comment]
UI stuff is last on my list, will do some UI modifications when the plugins are stable.

**Comment by manuelsongokuh** [comment]
ok OF COURSE, first STABLE after will free time to change it ok? 
thank you

**Comment by olear** [comment]
Busy until Sunday, but will fix most issues then.

**Comment by olear** [comment]
Will not split the Distort plugin.

**Comment by devernay** [comment]
@olear you can use the special parameter kNatronOfxParamStringSublabelName to set a sublabel. See Merge.cpp for an example.

**Comment by olear** [comment]
Reopen, Distort is getting big, should I split or not?

 * Polar
 * DePolar
 * Arc
 * Swirl
 * Implode
 * Edge
 * Emboss
 * Wave
 * Roll

**Comment by manuelsongokuh** [comment]
hello,
sincerity: i cant decide me,

my opinion:

actual
menu>filter>distort: polar, depolar, arc, swirl, edge, emboss, wave, roll.

idea A:
menu>filter>openfx-arena>distort: polar, depolar, arc, swirl, edge, emboss, wave, roll.

idea B:
menu>openfx-arena>distort: polar, depolar, arc, swirl, edge, emboss, wave, roll.

idea C:
menu>openfx-arena>distort: polar, depolar, arc, swirl, edge, wave.
menu>openfx-arena>filter: emboss, other effect of filter (roadmap)
menu>openfz-arena>trasform:roll, other effect of trasform (roadmap)

example from AE adobe:

3D Channel effects:
   3D Channel Extract effect
    Depth Matte effect
    Depth Of Field effect
    Fog 3D effect


Blur & Sharpen effects:
    Bilateral Blur effect
    Box Blur effect
    Camera Lens Blur effect
    Channel Blur effect
    Compound Blur effect
    Directional Blur effect
    Fast Blur effect
    Gaussian Blur effect
    Lens Blur effect
    Radial Blur effect
    Reduce Interlace Flicker effect
    Sharpen effect
    Smart Blur effect
    Unsharp Mask effect

Distort effects
    Bezier Warp effect
    Bulge effect
    Corner Pin effect
    Displacement Map effect
    Liquify effect
    Magnify effect
    Mesh Warp effect
    Mirror effect
    Offset effect
    Optics Compensation effect
    Polar Coordinates effect
    Reshape effect
    Ripple effect
    Smear effect
    Spherize effect
    Transform effect
    Turbulent Displace effect
    Twirl effect
    Warp effect
    Warp Stabilizer effect (CS5.5 and later)
    Wave Warp effect
etc etc


i write here for opinion only... ok?
:-)

**Comment by manuelsongokuh** [comment]
a theory:

if a plug containing 10 effects, this signigica that code has many lines, it would be difficult to find a bug ... or it will be very difficult to correct a bug?
summary:

--- Pro:
* For programmer: single code and grouped.

--- Cons:
* For customers use many times node ("distort-arc" + "distort-roll" + "distort-embross") is clear! it takes much time ... or it takes a lot of work



Instead other theory:

if a plug containing one effect, this means that code has a lot less code, it would be easy to find a bug .... or it will be easy to fix a bug?
summary:

--- Pro:
* For programmer: lightweight code or saving a lot lines, it can be easy to find bug?
* For customers working on one singular effect (parameter, value, etc.) this means that there is not scaring or confusing or easy to understand how to work with plug ...

--- Cons:
* For programmer: working a lot of code for separation but will once created code.

But first of all if you "search engine" filter as I wrote issue to natron:
https://github.com/MrKepzie/Natron/issues/649


because if it is "search engine" and filter, then this is the solution for "many plugs" singulars ..

but I remain "only" theory ..

for me: uhmm .... maybe it's better: each one contains 1 plug effect ..
We wait someone: what does people think, okay?

**Comment by manuelsongokuh** [comment]
keyboard shortcut "TAB" it' active search tha ok, then for me...

...my opinion, all plug has ONE effect, like as AE..
but need to test it test it, because i'm one person, better ask people if need to "single" or 1 plug containing 10 effects...

need to time to TEST ok?

**Comment by olear** [comment]
May split into individual plugins, but at the moment I'm not going to do anything before issue #58 is resolved, and I don't know what's wrong...

**Comment by manuelsongokuh** [comment]
ok, you need to tranquil, take a time for calm and find a bug..
maybe problem: distort have more effects: arc, polar, depolar, swirl, embross, roll, etc so this mean maybe there are conflict?...

i think try: you copy backup code and 1 plug for ONE effect: polar and test with transparency..
if pluf one with transparency will problem or not..

okay, for now need to calm for time free, not STRESS ok?

**Comment by olear** [comment]
Polar is now it's own plugin, https://github.com/olear/openfx-arena/commit/70d8893a4b08d8e5d3a60c3af1e55704ab53e0a9

Will split more.

**Comment by manuelsongokuh** [comment]
ok, for now first to try with issue transparency.. what is result? bug or worked?

**Comment by sozap** [comment]
What about having some split, but keep effects together when it make sense, like : 

-Polar/Depolar

-Swirl/implode (it would be best if they can cumulate (swirl + implode) ) and maybe wave.

-edge/emboss

-arc

-roll

something like that seems logical to me, what do you think ?

**Comment by olear** [comment]
Looks ok.

DePolar+Polar=Polar
Swirl+Implode+Wave = Warp
Arc=Arc
Roll=Roll

**Comment by manuelsongokuh** [comment]
@sozap that is good idea!
@olear : but need name : like as: "openfx-arena" or "ofxA" or other, because it's your sign 
or icon of openfx-arena: full green or different of natron nature, 
example of AE (adobe) has plug CC is from cycorefx, other VC is from VideoCopilot.
this is an example to say ok?
